[package]
name = "pingyang-desktop"
version = "0.1.0"
description = "平阳木版年画数字馆藏桌面端"
edition = "2021"

[lib]
name = "pingyang_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
